name: small_read
description: Human readable clear text data store with minimal symbol overhead.
version: 1.0.0
homepage: git@github.com:ltOgt/sr-dart.git
environment:
  sdk: '>=2.14.4 <3.0.0'
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
